### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by ans92** [ExplainableML/czsl#11]
Hi,
Thank you for this code. I want to ask do you have pre-trained models? As training is very time consuming so if I want to test the model I have to train it first. So if you have pre-trained model that it would be very helpful. Thank you.

**Comment by mancinimassimiliano** [comment]
I apologize for the super late reply: unfortunately, as for our private conversation, we do not have pre-trained models to share since merging CGE and CompCos codebases required re-adapting some parts of the code, and thus pre-trained models may not work off the shelf. In case of an issue in running the evaluation of this codebase, consider checking the [Co-CGE](https://github.com/ExplainableML/co-cge) one that has a flag "--fast_eval" for faster evaluation on the OW-CZSL setting.
