### ISSUE TITLE
The download link: 'https://www.cs.utexas.edu/~tushar/attribute-ops/attr-ops-data.tar.gz' can not be fetched

### ISSUE THREAD

**Issue by lisuyi** [ExplainableML/czsl#29]

**Comment by lisuyi** [comment]
I think I can use this link instead:  https://utexas.box.com/shared/static/h7ckk2gx5ykw53h8o641no8rdyi7185g.gz

**Comment by mancinimassimiliano** [comment]
Hi @lisuyi! 

Sorry for the very late reply, and thanks for spotting this issue, caused by a change in the attribute as operators [repo](https://github.com/Tushar-N/attributes-as-operators/commit/3372020afe137e79c95c0d35c5fbd5d966bd76f7). 

I fixed the link and now everything should work, but feel free to re-open the issue in case the problem is not fixed.
